### ISSUE TITLE
Wrong deserialization issue when using `listVoices()`

### ISSUE THREAD

**Issue by realkalash** [ZachHandley/elevenlabs_flutter#3]
[log] 12:40:7: Error: [Platform] Instance of 'UnknownApiException'
[log] #0      ElevenLabsAPI._handleError (package:elevenlabs_flutter/elevenlabs_flutter.dart:346:5)
      #1      ElevenLabsAPI.listVoices (package:elevenlabs_flutter/elevenlabs_flutter.dart:70:13)
elevenlabs_flutter.dart:70
      <asynchronous suspension>
      #2      _ElevenLabsConfigDialogState.loadVoices (package:***/features/elevenlabs_speech.dart:116:14)

To reproduce:
```dart
await ElevenlabsSpeech.elevenLabs.listVoices();
```

The problem is here:
```dart
for (dynamic voiceJson in responseList) {
        voices.add(Voice.fromJson(voiceJson)); // <--- fromJson fails
      }
```

```dart
FineTuning _$FineTuningFromJson(Map<String, dynamic> json) => FineTuning(
      fineTuningRequested: json['fine_tuning_requested'] as bool, // <-- type 'Null' is not a subtype of type 'bool' in type cast
```

**Comment by realkalash** [comment]
The same with `finetuning_state` -> type 'Null' is not a subtype of type 'String' in type cast

```dart
language: json['language'] == null
          ? null
          : Language.fromJson(json['language'] as Map<String, dynamic>), // <--- type 'String' is not a subtype of type 'Map<String, dynamic>' in type cast
```

also
```dart
Sharing _$SharingFromJson(Map<String, dynamic> json) => Sharing(
      clonedByCount: json['cloned_by_count'] as int,
      historyItemSampleId: json['history_item_sample_id'] as String, // <-- type 'Null' is not a subtype of type 'String' in type cast
```

and
```dart
Sharing _$SharingFromJson(Map<String, dynamic> json) => Sharing(
      clonedByCount: json['cloned_by_count'] as int,
      historyItemSampleId: json['history_item_sample_id'] as String?,
      likedByCount: json['liked_by_count'] as int,
      originalVoiceId: json['original_voice_id'] as String,
      publicOwnerId: json['public_owner_id'] as String,
      status: json['status'] as String,
      voiceId: json['voice_id'] as String, // <-- type 'Null' is not a subtype of type 'String' in type cast
```

And many others...

**Comment by martinmichaelsen** [comment]
I have the same problem!!!
